name: Quality Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  api-tests:
    name: Karate API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Executar testes Karate
        run: mvn clean test

      - name: Publicar relatório Karate
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/karate-reports/

  performance-smoke:
    name: k6 Performance Smoke
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Executar smoke de performance
        uses: grafana/run-k6-action@v1
        with:
          path: performance/k6/smoke.js
